/* GENERATED by scripts/sync-progress.mjs — do not edit by hand.
 *
 * Source: https://github.com/RaghhavMalani/leetcode-progress
 * Scanned 117 problem directories; 109 carry a parsed NOTES.md
 * header and 109 have a traced visualisation.
 *
 * Committed on purpose: the deployed site has no access to the other repo, so this
 * snapshot is what it reads. Re-run the script and commit after you solve things.
 */

export interface SolvedEntry {
  /** LeetCode problem number */
  num: number;
  /** directory name in the progress repo, e.g. "0042-trapping-rain-water" */
  dir: string;
  /** "easy" | "medium" | "hard", or "" if NOTES.md had no header */
  diff: string;
  /** the author's own fine-grained pattern label, e.g. "Two pointers · converging" */
  label: string;
  /** one of the 16 families used in that repo's PATTERNS.md */
  family: string;
  /** which languages the solution exists in */
  langs: readonly string[];
  /** a step-by-step traced HTML visualisation exists */
  viz: boolean;
  /** a written NOTES.md exists */
  notes: boolean;
}

export const PROGRESS_REPO = "https://github.com/RaghhavMalani/leetcode-progress";

/** Counted by scanning directories, not taken on trust from stats.json. */
export const PROGRESS_COUNTS = {
  total: 117,
  easy: 37,
  medium: 62,
  hard: 18,
  withNotes: 109,
  withViz: 109,
} as const;

/** What stats.json claims, for comparison. Null when absent or unparseable. */
export const PROGRESS_DECLARED = {"solved":101,"easy":32,"medium":54,"hard":15} as const;

export const SOLVED: readonly SolvedEntry[] = [
  { num: 1, dir: "0001-two-sum", diff: "easy", label: "Hash map · complement lookup", family: "Hashing", langs: ["py"], viz: true, notes: true },
  { num: 2, dir: "0002-add-two-numbers", diff: "medium", label: "Linked list · digit-by-digit carry", family: "Linked lists", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 3, dir: "0003-longest-substring-without-repeating-characters", diff: "medium", label: "Sliding window · variable size", family: "Two pointers & sliding window", langs: ["py"], viz: true, notes: true },
  { num: 14, dir: "0014-longest-common-prefix", diff: "easy", label: "Vertical scanning", family: "Two pointers & sliding window", langs: ["py"], viz: true, notes: true },
  { num: 19, dir: "0019-remove-nth-node-from-end-of-list", diff: "medium", label: "Linked list · two pointers with a gap", family: "Two pointers & sliding window", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 21, dir: "0021-merge-two-sorted-lists", diff: "easy", label: "Linked list · dummy head + merge", family: "Linked lists", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 22, dir: "0022-generate-parentheses", diff: "medium", label: "Backtracking · build-and-undo", family: "Backtracking", langs: ["py"], viz: true, notes: true },
  { num: 23, dir: "0023-merge-k-sorted-lists", diff: "hard", label: "Divide and conquer · pairwise merge", family: "Sorting & divide and conquer", langs: ["py"], viz: true, notes: true },
  { num: 36, dir: "0036-valid-sudoku", diff: "medium", label: "Hash sets · index-to-bucket mapping", family: "Hashing", langs: ["py"], viz: true, notes: true },
  { num: 39, dir: "0039-combination-sum", diff: "medium", label: "Backtracking · take / skip", family: "Backtracking", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 40, dir: "0040-combination-sum-ii", diff: "medium", label: "Backtracking · duplicate suppression", family: "Backtracking", langs: ["py"], viz: true, notes: true },
  { num: 42, dir: "0042-trapping-rain-water", diff: "hard", label: "Two pointers · converging", family: "Two pointers & sliding window", langs: ["py"], viz: true, notes: true },
  { num: 46, dir: "0046-permutations", diff: "medium", label: "Recursion · bottom-up construction (NOT backtracking)", family: "Backtracking", langs: ["py"], viz: true, notes: true },
  { num: 47, dir: "0047-permutations-ii", diff: "medium", label: "Backtracking · counter as state", family: "Backtracking", langs: ["py"], viz: true, notes: true },
  { num: 49, dir: "0049-group-anagrams", diff: "medium", label: "Hash map · canonical key", family: "Hashing", langs: ["py"], viz: true, notes: true },
  { num: 57, dir: "0057-insert-interval", diff: "medium", label: "Intervals · three-case scan", family: "Prefix sums & intervals", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 62, dir: "0062-unique-paths", diff: "medium", label: "Grid DP · rolling row", family: "Dynamic programming", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 70, dir: "0070-climbing-stairs", diff: "easy", label: "DP · Fibonacci with rolling variables", family: "Dynamic programming", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 75, dir: "0075-sort-colors", diff: "medium", label: "Three pointers · Dutch national flag", family: "Two pointers & sliding window", langs: ["py"], viz: true, notes: true },
  { num: 77, dir: "0077-combinations", diff: "medium", label: "Backtracking · loop form", family: "Backtracking", langs: ["java", "py"], viz: true, notes: true },
  { num: 78, dir: "0078-subsets", diff: "medium", label: "Backtracking · take / skip", family: "Backtracking", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 81, dir: "0081-search-in-rotated-sorted-array-ii", diff: "medium", label: "Binary search · rotated + duplicates", family: "Binary search", langs: ["py"], viz: true, notes: true },
  { num: 90, dir: "0090-subsets-ii", diff: "medium", label: "Backtracking · duplicate suppression", family: "Backtracking", langs: ["py"], viz: true, notes: true },
  { num: 92, dir: "0092-reverse-linked-list-ii", diff: "medium", label: "Linked list · partial reversal + seams", family: "Linked lists", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 94, dir: "0094-binary-tree-inorder-traversal", diff: "easy", label: "Tree traversal · explicit stack", family: "Trees", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 122, dir: "0122-best-time-to-buy-and-sell-stock-ii", diff: "medium", label: "Greedy · decompose into local gains", family: "Greedy", langs: ["py"], viz: true, notes: true },
  { num: 124, dir: "0124-binary-tree-maximum-path-sum", diff: "hard", label: "Tree DFS · return one thing, track another", family: "Trees", langs: ["py"], viz: true, notes: true },
  { num: 128, dir: "0128-longest-consecutive-sequence", diff: "medium", label: "Hash set · amortised scan", family: "Hashing", langs: ["py"], viz: true, notes: true },
  { num: 136, dir: "0136-single-number", diff: "easy", label: "Bit manipulation · XOR cancellation", family: "Bit manipulation", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 138, dir: "0138-copy-list-with-random-pointer", diff: "medium", label: "Hash map old→new · two-pass clone", family: "Hashing", langs: ["cpp", "java"], viz: true, notes: true },
  { num: 141, dir: "0141-linked-list-cycle", diff: "easy", label: "Fast & slow pointers · Floyd", family: "Two pointers & sliding window", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 143, dir: "0143-reorder-list", diff: "medium", label: "Linked list · compose three primitives", family: "Linked lists", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 146, dir: "0146-lru-cache", diff: "medium", label: "Design · hash map + doubly linked list", family: "Hashing", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 168, dir: "0168-excel-sheet-column-title", diff: "easy", label: "Math · bijective base conversion", family: "Math & number theory", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 206, dir: "0206-reverse-linked-list", diff: "easy", label: "Linked list · pointer rewiring", family: "Linked lists", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 217, dir: "0217-contains-duplicate", diff: "easy", label: "Hash set · membership", family: "Hashing", langs: ["py"], viz: true, notes: true },
  { num: 219, dir: "0219-contains-duplicate-ii", diff: "easy", label: "Sliding window · fixed size", family: "Two pointers & sliding window", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 237, dir: "0237-delete-node-in-a-linked-list", diff: "medium", label: "Linked list · impersonation trick", family: "Linked lists", langs: ["py"], viz: true, notes: true },
  { num: 238, dir: "0238-product-of-array-except-self", diff: "medium", label: "Prefix / suffix accumulation", family: "Prefix sums & intervals", langs: ["py"], viz: true, notes: true },
  { num: 242, dir: "0242-valid-anagram", diff: "easy", label: "Hash map · frequency count", family: "Hashing", langs: ["py"], viz: true, notes: true },
  { num: 287, dir: "0287-find-the-duplicate-number", diff: "medium", label: "Floyd cycle detection · fast & slow", family: "Two pointers & sliding window", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 288, dir: "0288-unique-word-abbreviation", diff: "medium", label: "Design · precompute a canonical key", family: "Hashing", langs: ["py"], viz: true, notes: true },
  { num: 291, dir: "0291-word-pattern-ii", diff: "medium", label: "Backtracking · bijection search", family: "Backtracking", langs: ["py"], viz: true, notes: true },
  { num: 304, dir: "0304-range-sum-query-2d-immutable", diff: "medium", label: "2D prefix sum · inclusion–exclusion", family: "Prefix sums & intervals", langs: ["py"], viz: true, notes: true },
  { num: 344, dir: "0344-reverse-string", diff: "easy", label: "Two pointers · converging", family: "Two pointers & sliding window", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 347, dir: "0347-top-k-frequent-elements", diff: "medium", label: "Bucket sort · frequency", family: "Hashing", langs: ["py"], viz: true, notes: true },
  { num: 387, dir: "0387-first-unique-character-in-a-string", diff: "easy", label: "Hash map · two-pass frequency", family: "Hashing", langs: ["py"], viz: true, notes: true },
  { num: 460, dir: "0460-lfu-cache", diff: "hard", label: "Design · three maps + per-frequency LRU lists", family: "Design", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 463, dir: "0463-island-perimeter", diff: "easy", label: "Grid DFS · flood fill", family: "Graphs, BFS & DFS", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 622, dir: "0622-design-circular-queue", diff: "medium", label: "Design · doubly linked list with sentinels", family: "Linked lists", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 628, dir: "0628-maximum-product-of-three-numbers", diff: "easy", label: "Sorting · exhaustive case analysis", family: "Math & number theory", langs: ["py"], viz: true, notes: true },
  { num: 682, dir: "0682-baseball-game", diff: "easy", label: "Stack · simulation with undo", family: "Stacks & monotonic stacks", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 703, dir: "0703-kth-largest-element-in-a-stream", diff: "easy", label: "Heap · bounded size-k min-heap", family: "Sorting & divide and conquer", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 704, dir: "0704-binary-search", diff: "easy", label: "Binary search · exact match", family: "Binary search", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 705, dir: "0705-design-hashset", diff: "easy", label: "Design · hash table internals", family: "Design", langs: ["py"], viz: true, notes: true },
  { num: 706, dir: "0706-design-hashmap", diff: "easy", label: "Design · hash table internals", family: "Design", langs: ["py"], viz: true, notes: true },
  { num: 739, dir: "0739-daily-temperatures", diff: "medium", label: "Monotonic stack · next greater element", family: "Stacks & monotonic stacks", langs: ["py"], viz: true, notes: true },
  { num: 773, dir: "0773-sliding-puzzle", diff: "hard", label: "BFS on a state graph", family: "Graphs, BFS & DFS", langs: ["py"], viz: true, notes: true },
  { num: 860, dir: "0860-lemonade-change", diff: "easy", label: "Greedy · spend the least flexible resource first", family: "Greedy", langs: ["cpp", "java"], viz: true, notes: true },
  { num: 867, dir: "0867-new-21-game", diff: "medium", label: "Probability DP · sliding window sum", family: "Two pointers & sliding window", langs: ["py"], viz: true, notes: true },
  { num: 912, dir: "0912-sort-an-array", diff: "medium", label: "Divide and conquer · merge sort", family: "Sorting & divide and conquer", langs: ["py"], viz: true, notes: true },
  { num: 934, dir: "0934-bitwise-ors-of-subarrays", diff: "medium", label: "Monotone bit operation · bounded frontier", family: "Bit manipulation", langs: ["py"], viz: true, notes: true },
  { num: 1071, dir: "1071-greatest-common-divisor-of-strings", diff: "easy", label: "Number theory analogy · gcd on lengths", family: "Math & number theory", langs: ["py"], viz: true, notes: true },
  { num: 1081, dir: "1081-smallest-subsequence-of-distinct-characters", diff: "medium", label: "Monotonic stack · greedy with a safety check", family: "Stacks & monotonic stacks", langs: ["cpp"], viz: true, notes: true },
  { num: 1260, dir: "1260-shift-2d-grid", diff: "easy", label: "Flatten · modular shift · unflatten", family: "Math & number theory", langs: ["cpp"], viz: true, notes: true },
  { num: 1288, dir: "1288-remove-covered-intervals", diff: "medium", label: "Intervals · sort key does the work", family: "Prefix sums & intervals", langs: ["py"], viz: true, notes: true },
  { num: 1291, dir: "1291-sequential-digits", diff: "medium", label: "Generate the small candidate set, then filter", family: "Greedy", langs: ["cpp"], viz: true, notes: true },
  { num: 1301, dir: "1301-number-of-paths-with-max-score", diff: "hard", label: "", family: "", langs: [], viz: false, notes: true },
  { num: 1331, dir: "1331-rank-transform-of-an-array", diff: "easy", label: "", family: "", langs: [], viz: false, notes: true },
  { num: 1344, dir: "1344-angle-between-hands-of-a-clock", diff: "medium", label: "Math · modular geometry", family: "Math & number theory", langs: ["py"], viz: true, notes: true },
  { num: 1358, dir: "1358-number-of-substrings-containing-all-three-characters", diff: "medium", label: "Sliding window · counting", family: "Two pointers & sliding window", langs: ["py"], viz: true, notes: true },
  { num: 1448, dir: "1448-maximum-69-number", diff: "easy", label: "Greedy · positional value", family: "Greedy", langs: ["py"], viz: true, notes: true },
  { num: 1464, dir: "1464-maximum-product-of-two-elements-in-an-array", diff: "easy", label: "Single pass · top-k tracking", family: "Math & number theory", langs: ["py"], viz: true, notes: true },
  { num: 1485, dir: "1485-clone-binary-tree-with-random-pointer", diff: "medium", label: "", family: "", langs: [], viz: false, notes: true },
  { num: 1631, dir: "1631-path-with-minimum-effort", diff: "medium", label: "Dijkstra · minimax path", family: "Graphs, BFS & DFS", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 1732, dir: "1732-find-the-highest-altitude", diff: "easy", label: "Prefix sum · running maximum", family: "Prefix sums & intervals", langs: ["py"], viz: true, notes: true },
  { num: 1833, dir: "1833-maximum-ice-cream-bars", diff: "medium", label: "Greedy · counting sort", family: "Greedy", langs: ["py"], viz: true, notes: true },
  { num: 1840, dir: "1840-maximum-building-height", diff: "hard", label: "Constraint propagation · two sweeps + geometry", family: "Prefix sums & intervals", langs: ["py"], viz: true, notes: true },
  { num: 1846, dir: "1846-maximum-element-after-decreasing-and-rearranging", diff: "medium", label: "Greedy · sort then climb", family: "Greedy", langs: ["py"], viz: true, notes: true },
  { num: 1863, dir: "1863-sum-of-all-subset-xor-totals", diff: "easy", label: "Bit counting · contribution technique", family: "Bit manipulation", langs: ["cpp", "java", "py"], viz: true, notes: true },
  { num: 1929, dir: "1929-concatenation-of-array", diff: "easy", label: "Index arithmetic · pre-sized output", family: "Math & number theory", langs: ["cpp", "java"], viz: true, notes: true },
  { num: 1967, dir: "1967-number-of-strings-that-appear-as-substrings-in-word", diff: "easy", label: "String matching · know what your library does", family: "Brute force done right", langs: ["py"], viz: true, notes: true },
  { num: 1979, dir: "1979-find-greatest-common-divisor-of-array", diff: "easy", label: "Number theory · Euclidean algorithm", family: "Math & number theory", langs: ["cpp"], viz: true, notes: true },
  { num: 2095, dir: "2095-delete-the-middle-node-of-a-linked-list", diff: "medium", label: "Fast & slow pointers · find the middle", family: "Two pointers & sliding window", langs: ["py"], viz: true, notes: true },
  { num: 2133, dir: "2133-number-of-pairs-of-strings-with-concatenation-equal-to-target", diff: "medium", label: "Brute force · index vs value identity", family: "Brute force done right", langs: ["py"], viz: true, notes: true },
  { num: 2144, dir: "2144-minimum-cost-of-buying-candies-with-discount", diff: "easy", label: "Greedy · sort descending, take every third", family: "Greedy", langs: ["cpp"], viz: true, notes: true },
  { num: 2161, dir: "2161-partition-array-according-to-given-pivot", diff: "medium", label: "Stable three-way partition", family: "Two pointers & sliding window", langs: ["py"], viz: true, notes: true },
  { num: 2196, dir: "2196-create-binary-tree-from-descriptions", diff: "medium", label: "Hash map · build a structure from edges", family: "Hashing", langs: ["py"], viz: true, notes: true },
  { num: 2450, dir: "2450-minimum-replacements-to-sort-the-array", diff: "hard", label: "Greedy from the right · equal splitting", family: "Greedy", langs: ["c"], viz: true, notes: true },
  { num: 2492, dir: "2492-minimum-score-of-a-path-between-two-cities", diff: "medium", label: "", family: "", langs: [], viz: false, notes: true },
  { num: 2503, dir: "2503-longest-subarray-with-maximum-bitwise-and", diff: "medium", label: "Observation-driven · monotone operation", family: "Greedy", langs: ["py"], viz: true, notes: true },
  { num: 2574, dir: "2574-left-and-right-sum-differences", diff: "easy", label: "Prefix sum · total minus prefix", family: "Prefix sums & intervals", langs: ["py"], viz: true, notes: true },
  { num: 2685, dir: "2685-count-the-number-of-complete-components", diff: "medium", label: "Connected components + a counting criterion", family: "Graphs, BFS & DFS", langs: ["cpp"], viz: true, notes: true },
  { num: 2807, dir: "2807-insert-greatest-common-divisors-in-linked-list", diff: "medium", label: "Linked list · insert between pairs", family: "Linked lists", langs: ["cpp"], viz: true, notes: true },
  { num: 2812, dir: "2812-find-the-safest-path-in-a-grid", diff: "medium", label: "Multi-source BFS + maximin Dijkstra", family: "Graphs, BFS & DFS", langs: ["py"], viz: true, notes: true },
  { num: 3020, dir: "3020-find-the-maximum-number-of-elements-in-subset", diff: "medium", label: "Frequency map · chain following", family: "Hashing", langs: ["py"], viz: true, notes: true },
  { num: 3221, dir: "3221-find-the-peaks", diff: "easy", label: "Array scan · local property", family: "Math & number theory", langs: ["py"], viz: true, notes: true },
  { num: 3336, dir: "3336-find-the-number-of-subsequences-with-equal-gcd", diff: "hard", label: "DP over a bounded state (gcd × gcd)", family: "Dynamic programming", langs: ["cpp"], viz: true, notes: true },
  { num: 3499, dir: "3499-maximize-active-section-with-trade-i", diff: "medium", label: "Run-length scan · pair of adjacent runs", family: "Prefix sums & intervals", langs: ["cpp"], viz: true, notes: true },
  { num: 3501, dir: "3501-maximize-active-section-with-trade-ii", diff: "hard", label: "", family: "", langs: [], viz: false, notes: true },
  { num: 3513, dir: "3513-number-of-unique-xor-triplets-i", diff: "medium", label: "Bit reasoning · closed form", family: "Bit manipulation", langs: ["py"], viz: true, notes: true },
  { num: 3514, dir: "3514-number-of-unique-xor-triplets-ii", diff: "medium", label: "", family: "", langs: [], viz: false, notes: true },
  { num: 3532, dir: "3532-path-existence-queries-in-a-graph-i", diff: "medium", label: "Sorted structure collapses a graph", family: "Graphs, BFS & DFS", langs: ["py"], viz: true, notes: true },
  { num: 3534, dir: "3534-path-existence-queries-in-a-graph-ii", diff: "hard", label: "Sort + greedy farthest + binary lifting", family: "Graphs, BFS & DFS", langs: ["cpp"], viz: true, notes: true },
  { num: 3536, dir: "3536-maximum-product-of-two-digits", diff: "easy", label: "", family: "", langs: [], viz: false, notes: true },
  { num: 3558, dir: "3558-number-of-ways-to-assign-edge-weights-i", diff: "medium", label: "BFS height + parity counting", family: "Graphs, BFS & DFS", langs: ["py"], viz: true, notes: true },
  { num: 3559, dir: "3559-number-of-ways-to-assign-edge-weights-ii", diff: "hard", label: "Binary lifting LCA + parity counting", family: "Trees", langs: ["py"], viz: true, notes: true },
  { num: 3614, dir: "3614-process-string-with-special-operations-ii", diff: "hard", label: "Forward lengths + backward index mapping", family: "Math & number theory", langs: ["py"], viz: true, notes: true },
  { num: 3620, dir: "3620-network-recovery-pathways", diff: "hard", label: "Binary search on the answer + DAG shortest path", family: "Binary search", langs: ["py"], viz: true, notes: true },
  { num: 3689, dir: "3689-maximum-total-subarray-value-i", diff: "medium", label: "Observation · the constraint that is not there", family: "Greedy", langs: ["py"], viz: true, notes: true },
  { num: 3699, dir: "3699-number-of-zigzag-arrays-i", diff: "hard", label: "DP with direction state + prefix-sum transitions", family: "Dynamic programming", langs: ["py"], viz: true, notes: true },
  { num: 3700, dir: "3700-number-of-zigzag-arrays-ii", diff: "hard", label: "Matrix exponentiation of a linear recurrence", family: "Dynamic programming", langs: ["py"], viz: true, notes: true },
  { num: 3737, dir: "3737-count-subarrays-with-majority-element-i", diff: "medium", label: "Brute force with incremental state", family: "Brute force done right", langs: ["py"], viz: true, notes: true },
  { num: 3739, dir: "3739-count-subarrays-with-majority-element-ii", diff: "hard", label: "+1/−1 transform · prefix sums · Fenwick tree", family: "Prefix sums & intervals", langs: ["py"], viz: true, notes: true },
  { num: 3751, dir: "3751-total-waviness-of-numbers-in-range-i", diff: "medium", label: "", family: "", langs: [], viz: false, notes: true },
  { num: 3753, dir: "3753-total-waviness-of-numbers-in-range-ii", diff: "hard", label: "Digit DP · tight / started / carried context", family: "Dynamic programming", langs: ["py"], viz: true, notes: true },
  { num: 3754, dir: "3754-concatenate-non-zero-digits-and-multiply-by-sum-i", diff: "easy", label: "Digit manipulation · single pass, two accumulators", family: "Math & number theory", langs: ["py"], viz: true, notes: true },
];
